/// <reference path="./sql.d.ts" />

import { createHash } from "node:crypto";
import type { MigrationMeta } from "drizzle-orm/migrator";
import migration0Sql from "../drizzle/20260730103433_initial/migration.sql" with { type: "text" };
import migration1Sql from "../drizzle/20260730113243_regular_pretty_boy/migration.sql" with {
	type: "text",
};

// Generated by scripts/generate.ts. The SQL stays embedded so Bun's server,
// CLI, and compiled executable builds need no loose migration files at runtime.

function migration(name: string, folderMillis: number, source: string): MigrationMeta {
	return {
		name,
		folderMillis,
		hash: createHash("sha256").update(source).digest("hex"),
		bps: true,
		sql: source.split("--> statement-breakpoint"),
	};
}

export const MIGRATIONS: MigrationMeta[] = [
	migration("20260730103433_initial", Date.UTC(2026, 6, 30, 10, 34, 33), migration0Sql),
	migration("20260730113243_regular_pretty_boy", Date.UTC(2026, 6, 30, 11, 32, 43), migration1Sql),
];
