import type { Store } from "@pstdio/pocketcoder-runtime-contracts";
import { createDatabaseContext, createLifecycle } from "./database/context";
import { createWorkspaceWaiter } from "./database/workspace-changes";
import { createAuth } from "./modules/auth/repository";
import { createConversations } from "./modules/conversations/repository";
import { createLogs } from "./modules/logs/repository";
import { createNetworkAudit } from "./modules/network-audit/repository";
import { createOutbox } from "./modules/outbox/repository";
import { createOutputs } from "./modules/outputs/repository";
import { createCheckpoints } from "./modules/persistence/checkpoints";
import { createOperations } from "./modules/persistence/operations";
import { createStorage } from "./modules/persistence/storage";
import { createTemplates } from "./modules/templates/repository";
import { createTerminals } from "./modules/terminals/repository";
import { createWarmPools } from "./modules/warm-pools/repository";
import { createAdmission } from "./modules/workspaces/admission";
import { createWorkspaces } from "./modules/workspaces/repository";
import { createTransitions } from "./modules/workspaces/transitions";

export class PostgresStore implements Store {
  constructor(databaseUrl: string, schema = "pocketcoder") {
    const context = createDatabaseContext(databaseUrl, schema);
    const lifecycle = createLifecycle(context);
    this.init = lifecycle.init;
    this.close = lifecycle.close;
    this.acquireCoordinatorLease = lifecycle.acquireCoordinatorLease;
    const templates = createTemplates(context);
    this.upsertTemplate = templates.upsertTemplate;
    this.listTemplates = templates.listTemplates;
    this.getTemplate = templates.getTemplate;
    this.setTemplateStatus = templates.setTemplateStatus;
    const auth = createAuth(context);
    this.createPrincipal = auth.createPrincipal;
    this.getPrincipalByName = auth.getPrincipalByName;
    this.listPrincipals = auth.listPrincipals;
    this.updatePrincipal = auth.updatePrincipal;
    this.setPrincipalDisabled = auth.setPrincipalDisabled;
    this.insertMachineKey = auth.insertMachineKey;
    this.getMachineKeyWithPrincipal = auth.getMachineKeyWithPrincipal;
    this.revokeMachineKey = auth.revokeMachineKey;
    this.touchMachineKey = auth.touchMachineKey;
    const workspaces = createWorkspaces(context);
    this.insertWorkspace = workspaces.insertWorkspace;
    this.getWorkspaceByIdempotency = workspaces.getWorkspaceByIdempotency;
    this.getWorkspace = workspaces.getWorkspace;
    this.listWorkspaces = workspaces.listWorkspaces;
    const admission = createAdmission(context);
    this.listQueuedHeads = admission.listQueuedHeads;
    this.listNonterminal = admission.listNonterminal;
    this.countActive = admission.countActive;
    this.countQueued = admission.countQueued;
    this.claimWorkspaceAdmission = admission.claimWorkspaceAdmission;
    const transitions = createTransitions(context);
    this.updateWorkspace = transitions.updateWorkspace;
    this.transition = transitions.transition;
    this.listStateHistory = transitions.listStateHistory;
    const storage = createStorage(context);
    this.getWorkspaceStorage = storage.getWorkspaceStorage;
    this.insertWorkspaceStorage = storage.insertWorkspaceStorage;
    this.getStorage = storage.getStorage;
    this.updateWorkspaceStorage = storage.updateWorkspaceStorage;
    const checkpoints = createCheckpoints(context);
    this.getCheckpoint = checkpoints.getCheckpoint;
    this.insertCheckpoint = checkpoints.insertCheckpoint;
    this.listCheckpoints = checkpoints.listCheckpoints;
    this.updateCheckpoint = checkpoints.updateCheckpoint;
    const operations = createOperations(context);
    this.insertOperation = operations.insertOperation;
    this.getOperation = operations.getOperation;
    this.getOperationByIdempotency = operations.getOperationByIdempotency;
    this.listIncompleteOperations = operations.listIncompleteOperations;
    this.updateOperation = operations.updateOperation;
    this.checkpointUsage = operations.checkpointUsage;
    this.countIncompleteOperations = operations.countIncompleteOperations;
    const warmPools = createWarmPools(context);
    this.getWarmPoolRuntime = warmPools.getWarmPoolRuntime;
    this.insertWarmPoolRuntime = warmPools.insertWarmPoolRuntime;
    this.listWarmPoolRuntimes = warmPools.listWarmPoolRuntimes;
    this.updateWarmPoolRuntime = warmPools.updateWarmPoolRuntime;
    this.claimWarmPoolRuntime = warmPools.claimWarmPoolRuntime;
    const outputs = createOutputs(context);
    this.appendOutput = outputs.appendOutput;
    this.listOutputs = outputs.listOutputs;
    const logs = createLogs(context);
    this.appendLogs = logs.appendLogs;
    this.readLogs = logs.readLogs;
    this.readLogTail = logs.readLogTail;
    const networkAudit = createNetworkAudit(context);
    this.appendNetworkEvents = networkAudit.appendNetworkEvents;
    this.readNetworkEvents = networkAudit.readNetworkEvents;
    const conversations = createConversations(context);
    this.appendConversationMessage = conversations.appendConversationMessage;
    this.readConversation = conversations.readConversation;
    this.getConversationState = conversations.getConversationState;
    this.setConversationExpiry = conversations.setConversationExpiry;
    this.deleteConversation = conversations.deleteConversation;
    this.pruneExpiredConversations = conversations.pruneExpiredConversations;
    const terminals = createTerminals(context);
    this.openTerminalSession = terminals.openTerminalSession;
    this.getTerminalSession = terminals.getTerminalSession;
    this.closeTerminalSession = terminals.closeTerminalSession;
    this.listTerminalSessions = terminals.listTerminalSessions;
    const outbox = createOutbox(context);
    this.claimDueEvents = outbox.claimDueEvents;
    this.markEventDelivered = outbox.markEventDelivered;
    this.markEventFailed = outbox.markEventFailed;
    this.appendEvent = outbox.appendEvent;
    this.waitForWorkspaceChange = createWorkspaceWaiter(context, workspaces.getWorkspace);
  }
  readonly init: Store["init"];
  readonly close: Store["close"];
  readonly acquireCoordinatorLease: Store["acquireCoordinatorLease"];
  readonly upsertTemplate: Store["upsertTemplate"];
  readonly listTemplates: Store["listTemplates"];
  readonly getTemplate: Store["getTemplate"];
  readonly setTemplateStatus: Store["setTemplateStatus"];
  readonly createPrincipal: Store["createPrincipal"];
  readonly getPrincipalByName: Store["getPrincipalByName"];
  readonly listPrincipals: Store["listPrincipals"];
  readonly updatePrincipal: Store["updatePrincipal"];
  readonly setPrincipalDisabled: Store["setPrincipalDisabled"];
  readonly insertMachineKey: Store["insertMachineKey"];
  readonly getMachineKeyWithPrincipal: Store["getMachineKeyWithPrincipal"];
  readonly revokeMachineKey: Store["revokeMachineKey"];
  readonly touchMachineKey: Store["touchMachineKey"];
  readonly insertWorkspace: Store["insertWorkspace"];
  readonly getWorkspaceByIdempotency: Store["getWorkspaceByIdempotency"];
  readonly getWorkspace: Store["getWorkspace"];
  readonly listWorkspaces: Store["listWorkspaces"];
  readonly listQueuedHeads: Store["listQueuedHeads"];
  readonly listNonterminal: Store["listNonterminal"];
  readonly countActive: Store["countActive"];
  readonly countQueued: Store["countQueued"];
  readonly claimWorkspaceAdmission: Store["claimWorkspaceAdmission"];
  readonly updateWorkspace: Store["updateWorkspace"];
  readonly transition: Store["transition"];
  readonly listStateHistory: Store["listStateHistory"];
  readonly getWorkspaceStorage: Store["getWorkspaceStorage"];
  readonly insertWorkspaceStorage: Store["insertWorkspaceStorage"];
  readonly getStorage: Store["getStorage"];
  readonly updateWorkspaceStorage: Store["updateWorkspaceStorage"];
  readonly getCheckpoint: Store["getCheckpoint"];
  readonly insertCheckpoint: Store["insertCheckpoint"];
  readonly listCheckpoints: Store["listCheckpoints"];
  readonly updateCheckpoint: Store["updateCheckpoint"];
  readonly insertOperation: Store["insertOperation"];
  readonly getOperation: Store["getOperation"];
  readonly getOperationByIdempotency: Store["getOperationByIdempotency"];
  readonly listIncompleteOperations: Store["listIncompleteOperations"];
  readonly updateOperation: Store["updateOperation"];
  readonly checkpointUsage: Store["checkpointUsage"];
  readonly countIncompleteOperations: Store["countIncompleteOperations"];
  readonly getWarmPoolRuntime: Store["getWarmPoolRuntime"];
  readonly insertWarmPoolRuntime: Store["insertWarmPoolRuntime"];
  readonly listWarmPoolRuntimes: Store["listWarmPoolRuntimes"];
  readonly updateWarmPoolRuntime: Store["updateWarmPoolRuntime"];
  readonly claimWarmPoolRuntime: Store["claimWarmPoolRuntime"];
  readonly appendOutput: Store["appendOutput"];
  readonly listOutputs: Store["listOutputs"];
  readonly appendLogs: Store["appendLogs"];
  readonly readLogs: Store["readLogs"];
  readonly readLogTail: Store["readLogTail"];
  readonly appendNetworkEvents: Store["appendNetworkEvents"];
  readonly readNetworkEvents: Store["readNetworkEvents"];
  readonly appendConversationMessage: Store["appendConversationMessage"];
  readonly readConversation: Store["readConversation"];
  readonly getConversationState: Store["getConversationState"];
  readonly setConversationExpiry: Store["setConversationExpiry"];
  readonly deleteConversation: Store["deleteConversation"];
  readonly pruneExpiredConversations: Store["pruneExpiredConversations"];
  readonly openTerminalSession: Store["openTerminalSession"];
  readonly getTerminalSession: Store["getTerminalSession"];
  readonly closeTerminalSession: Store["closeTerminalSession"];
  readonly listTerminalSessions: Store["listTerminalSessions"];
  readonly claimDueEvents: Store["claimDueEvents"];
  readonly markEventDelivered: Store["markEventDelivered"];
  readonly markEventFailed: Store["markEventFailed"];
  readonly appendEvent: Store["appendEvent"];
  readonly waitForWorkspaceChange: Store["waitForWorkspaceChange"];
}
