apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../server
patches:
  - target:
      kind: Service
      name: pocketcoder-server
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          service.beta.kubernetes.io/do-loadbalancer-protocol: https
          service.beta.kubernetes.io/do-loadbalancer-certificate-name: REPLACE_DIGITALOCEAN_CERTIFICATE_NAME
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: http
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "7080"
          service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: /readyz
      - op: replace
        path: /spec/type
        value: LoadBalancer
      - op: add
        path: /spec/loadBalancerSourceRanges
        value:
          - REPLACE_ALLOWED_SOURCE_CIDR
      - op: replace
        path: /spec/ports
        value:
          - name: https
            protocol: TCP
            port: 443
            targetPort: http
