import { readdir } from "node:fs/promises";
import { join, resolve } from "node:path";

const packageRoot = resolve(import.meta.dir, "..");
const drizzle = Bun.spawn(["bunx", "drizzle-kit", "generate", ...process.argv.slice(2)], {
	cwd: packageRoot,
	stdout: "inherit",
	stderr: "inherit",
});

if ((await drizzle.exited) !== 0) process.exit(1);

const migrationsRoot = join(packageRoot, "drizzle");
const migrationNames = (
	await readdir(migrationsRoot, {
		withFileTypes: true,
	})
)
	.filter((entry) => entry.isDirectory() && /^\d{14}_.+/.test(entry.name))
	.map((entry) => entry.name)
	.sort();

const imports = migrationNames
	.map(
		(name, index) =>
			`import migration${index}Sql from "../drizzle/${name}/migration.sql" with { type: "text" };`,
	)
	.join("\n");

const entries = migrationNames
	.map((name, index) => {
		const timestamp = name.slice(0, 14);
		const parts = [
			Number(timestamp.slice(0, 4)),
			Number(timestamp.slice(4, 6)) - 1,
			Number(timestamp.slice(6, 8)),
			Number(timestamp.slice(8, 10)),
			Number(timestamp.slice(10, 12)),
			Number(timestamp.slice(12, 14)),
		];
		return `\tmigration(${JSON.stringify(name)}, Date.UTC(${parts.join(", ")}), migration${index}Sql),`;
	})
	.join("\n");

const manifest = `/// <reference path="./sql.d.ts" />

import { createHash } from "node:crypto";
import type { MigrationMeta } from "drizzle-orm/migrator";
${imports}

// Generated by scripts/generate.ts. The SQL stays embedded so Bun's server,
// CLI, and compiled executable builds need no loose migration files at runtime.

function migration(name: string, folderMillis: number, source: string): MigrationMeta {
\treturn {
\t\tname,
\t\tfolderMillis,
\t\thash: createHash("sha256").update(source).digest("hex"),
\t\tbps: true,
\t\tsql: source.split("--> statement-breakpoint"),
\t};
}

export const MIGRATIONS: MigrationMeta[] = [
${entries}
];
`;

await Bun.write(join(packageRoot, "src/migrations.ts"), manifest);
console.log(`Updated embedded manifest with ${migrationNames.length} migration(s).`);
